name: Build and Push Vexa Lite

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
      - master
    paths:
      - 'docker/lite/**'

jobs:
  build-and-push-lite:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Vexa core repository
        uses: actions/checkout@v4
        with:
          repository: Vexa-ai/vexa  # We check out the exact Vexa core repository to get its code
          ref: main

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Replace teams.live.com with teams.microsoft.com
        run: |
          find . -type f -not -path "*/\.git/*" -exec sed -i 's/teams.live.com/teams.microsoft.com/g' {} +

      - name: Inject Proxy to Browser Args
        run: |
          sed -i 's/const baseBrowserArgs = \[/const baseBrowserArgs = \[\n  "--proxy-server=http:\/\/10.81.105.12:8080",/' services/vexa-bot/core/src/constans.ts

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: chosenwar/vexa-lite
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # build context is the vexa core repo
          file: docker/lite/Dockerfile.lite # point to the lite Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
